from __future__ import annotations

import logging
from dataclasses import dataclass

logger = logging.getLogger("the13th.ai_writer_service")


@dataclass
class GeneratedReply:
    subject: str
    body: str


class AIWriterService:
    """Lightweight, deterministic AI writer stub for simulation.

    In a production tenant this would call your configured LLM provider.
    """

    def generate_reply(self, thread_summary: str, last_message: str) -> GeneratedReply:
        last_excerpt = (last_message or "").strip()
        if not last_excerpt:
            last_excerpt = "your recent inquiry"

        subject = f"Re: {last_excerpt[:60]}"
        body = (
            "Hi there,\n\n"
            "This is a simulated AI reply inside THE13TH. In a live tenant, "
            "this text would be generated by your configured AI writer.\n\n"
            f"Thread summary: {thread_summary[:240]}\n\n"
            "Best,\n"
            "THE13TH Assistant"
        )

        logger.info("Generated simulated reply subject='%s'", subject)
        return GeneratedReply(subject=subject, body=body)
